116 how to configure sql params for cold chain
openmsupply/notify pull request #123
Opened 2023-09-13 00:25 UTC by jmbrunskill

Closes #116

# 👩🏻‍💻 What does this PR do?
 

Add ability to configure sql recipients to notification configs

# 🧪 How has/should this change been tested?

## 💌 Any notes for the reviewer?

2023-09-14 04:49 UTC, jmbrunskill commented on frontend/packages/common/src/utils/tera/TeraUtils.ts
> +      console.log('parameter parsing error', e, teraJson);
I think this is ok for now. Shouldn't happen if they code is working correctly!

2023-09-14 04:52 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
> +  const requiredParams = (sqlRecipientLists?.nodes ?? [])
At the moment, requiredParams can be filled in, but it doesn't stop you from saving if they are not filled it.
This seem okish for now. I'd like to be able to warn the user at least, but being able to save a draft while you figure out what params you want to use or something.
Adding a test function would be great too but not in scope for this PR.

2023-09-14 04:54 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditPage.tsx
> +  sqlRecipientListIds: seed?.sqlRecipientListIds ?? [],
I think recipient management should be part of the base config, and shouldn't need to parse it here.
I think I'll tackle this another PR though...

2023-09-14 04:56 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
> +    configurationData: JSON.stringify(config),
I don't think it hurts to put the whole Config object in (including ID etc)
Thoughts? Saves important things being missed, and having lots of places to update when adding a new field.

2023-09-20 23:42 UTC, mark-prins requested changes
🎉  that's very nice! I think is good to go once the validation is changed. I have managed to get a few errors, haven't reproduced though, so let's ignore that.

I would appreciate some instructions / readme / helper text - about constructing a query, what makes parameters required, where to configure database connection, what are the allowable types. Nothing fancy or comprehensive, but some tips would be much appreciated.

I've made a few UI tweaks in this [suggestion branch](https://github.com/openmsupply/notify/compare/116-how-to-configure-sql-params-for-cold-chain...116-how-to-configure-sql-params-suggestion)

I've also removed the console errors and warnings

You might want to add a button to the SQL recipients edit page which opens the parameters panel.
I'm editing and have closed it.. giving me this, with no way to update the params again

<img width="1269" alt="Screenshot 2023-09-21 at 11 35 14 AM" src="https://github.com/openmsupply/notify/assets/9192912/3657450f-25d2-4e5f-a0af-61a4d96b1a67">

( or keep it open and remove the close button 🤷 )

Perhaps a translation for this text?

<img width="256" alt="Screenshot 2023-09-21 at 8 49 57 AM" src="https://github.com/openmsupply/notify/assets/9192912/228af9dd-f525-4a0f-898b-5ebd3c58fb66">

2023-09-20 23:42 UTC, mark-prins commented on frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
> +  const requiredParams = (sqlRecipientLists?.nodes ?? [])
Can you add some validation? It's a bit odd being told that there are required fields but they aren't. If not, remove the 'required' asterix 🤷

2023-09-20 23:42 UTC, mark-prins commented on frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditPage.tsx
> +  parsedParameters: seed?.parsedParameters ?? {},
down in line 83 the `sqlRecipientListIds` needs to be added methinks:

```
    // no recipients selected
    (!draft.recipientListIds.length &&
      !draft.recipientIds.length &&
      !draft.sqlRecipientListIds.length);
```

2023-09-20 23:42 UTC, mark-prins commented on frontend/packages/system/src/Notifications/Pages/ColdChain/parseConfig.ts
> +    configurationData: JSON.stringify(config),
I think it's better - destructuring only some properties could well lead to missing some out which are needed

2023-09-20 23:42 UTC, mark-prins commented on frontend/packages/system/src/Notifications/Pages/Base/NotificationDetailPanel.tsx
> +                    backgroundColor: 'white',
so that the colour is picked from the theme, rather than a hard coded `white` string
```suggestion
                    backgroundColor: 'background.white',
```

2023-09-21 01:03 UTC, jmbrunskill commented
> You might want to add a button to the SQL recipients edit page which opens the parameters panel.
> I'm editing and have closed it.. giving me this, with no way to update the params again

There is a button here, but it's good feedback. I'll put in the parameters button at the top like I did on the Config Edit Page...
![image](https://github.com/openmsupply/notify/assets/8287373/de7c2d93-aa19-4c1a-bc0f-d705a616b847)

2023-09-21 02:16 UTC, mark-prins commented
> There is a button here

oh. heh.. I saw that and didn't try to click. I was already editing the sql query, so didn't think I needed to click 'edit'!
perhaps use a text+icon button?
( also, the vertical alignment of the button is a bit off wrt the text.. )

2023-09-21 03:06 UTC, jmbrunskill commented
> > There is a button here
> 
> oh. heh.. I saw that and didn't try to click. I was already editing the sql query, so didn't think I needed to click 'edit'! perhaps use a text+icon button? ( also, the vertical alignment of the button is a bit off wrt the text.. )

https://github.com/openmsupply/notify/issues/142

I think this is a better solution, as it will be more consistent :)

2023-09-21 03:08 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationAppBar.tsx
> +          setSelection={({
Nice, have merged.

2023-09-21 03:11 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/Base/NotificationDetailPanel.tsx
> +                    backgroundColor: 'white',
Cool thanks! Didn't realise the difference

2023-09-21 03:12 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/ColdChain/CCNotificationEditPage.tsx
> +  parsedParameters: seed?.parsedParameters ?? {},
Good catch thanks!

2023-09-21 04:12 UTC, mark-prins approved these changes
👍  thanks for changes! looking good

2023-09-21 04:19 UTC, jmbrunskill commented
> I would appreciate some instructions / readme / helper text - about constructing a query, what makes parameters required, where to configure database connection, what are the allowable types. Nothing fancy or comprehensive, but some tips would be much appreciated.

How does this look?
https://github.com/openmsupply/notify/pull/123/commits/fc61a25904182f2205a0c90325718b375bdf3bf7

Planning to create a docs website at some stage, which can be a bit prettier, but hopefully this fills the immediate hole?
Would like to do some more `inline` help things like suggested with `i` icon, not sure if it fits in our current MVP mode though.

2023-09-21 04:30 UTC, jmbrunskill commented on frontend/packages/system/src/Notifications/Pages/Base/BaseNotificationEditPage.tsx
> +  const requiredParams = (sqlRecipientLists?.nodes ?? [])
Have added the validation in for this.
I think in future this might get more complicated, but for now it's good the have the validation.
Mai is keen for a save as draft idea, which would allow you to save the config even with missing things so you can keep working on it later. See: #114 We'll also want some kind of `test` like we have for sql recipients (assuming we don't run out of budget)

2023-09-21 04:30 UTC, merged