124 sql query mangement
openmsupply/notify pull request #141
Opened 2023-09-21 00:51 UTC by jmbrunskill

Partially Closes #124 - Repo and Service only.

Note: also created a refactor issue https://github.com/openmsupply/notify/issues/140 given we're accumulating a lot of copy and pasted code validation code...

# 👩🏻‍💻 What does this PR do?
 

 (these queries will be used with in other Notification Configs, primarily `ScheduledNotification`)
- [ ] Add a repository for `notification_query`
- [ ] Add a service `notification_query_service`

# 🧪 How has/should this change been tested?

## 💌 Any notes for the reviewer?

2023-09-22 05:42 UTC, jmbrunskill commented on backend/graphql/notification_query/src/lib.rs
> +    pub async fn notification_querys(
Should this be `notification_queries`?
I quite like that a search for `notification_query` would find this, but also feels kind of wrong...

2023-09-22 05:48 UTC, jmbrunskill commented on backend/util/src/validate.rs
> +    static ref SPECIAL_CHARS_RE: Regex = Regex::new(r"[^ 0-9A-Za-z_\-@.+:/(),&]").unwrap();
I want to be able to create a name like `mSupply users, with region and country`

2023-09-27 23:41 UTC, roxy-dao requested changes
Looks good James! Just a few comments (:

2023-09-27 23:41 UTC, roxy-dao commented on backend/graphql/notification_query/src/mutations/update.rs
> +    pub required_parameters: Option<Vec<String>>,
Does this need to be an Option? Can't just check if vec is empty?

2023-09-27 23:41 UTC, roxy-dao commented on backend/graphql/notification_query/src/types/notification_query.rs
> +pub enum NotificationQuerysResponse {
NotificationQueries 😉

2023-09-27 23:41 UTC, roxy-dao commented on backend/repository/src/db_diesel/notification_query_row.rs
> +*/
delete?

2023-09-27 23:41 UTC, roxy-dao commented on backend/service/src/notification_query/tests/create.rs
> +        if !result.is_ok() {
Do you need to check this in create success test? 🤔

2023-09-27 23:41 UTC, roxy-dao commented on backend/service/src/notification_query/tests/update.rs
> +        assert_eq!(updated_notification_query.name, "name_for_id1".to_string());
There's an inline_edit function in om that allows you to edit the fields that have been changed for original row and check against updated row

2023-09-27 23:41 UTC, roxy-dao commented on backend/service/src/notification_query/validate.rs
> +    Ok(name.trim().len() >= 3 && name.len() <= 70)
```suggestion
    Ok(name.trim().len() >= 3 && name.trim().len() <= 70)
```?

2023-09-27 23:41 UTC, roxy-dao commented on backend/util/src/validate.rs
> +    static ref SPECIAL_CHARS_RE: Regex = Regex::new(r"[^ 0-9A-Za-z_\-@.+:/(),&]").unwrap();
Tried using regex checker for this... but it's not giving me any matches 😭

2023-09-28 02:16 UTC, jmbrunskill commented on backend/graphql/notification_query/Cargo.toml
> +edition = "2018"
If I set it to 2021 (this is the new default) I get this message

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

Haven't looked into it more deeply yet maybe `workspace.resolver = "2"` is somehow awesome for us?

2023-09-28 02:17 UTC, jmbrunskill commented on backend/graphql/notification_query/src/mutations/update.rs
> +    pub required_parameters: Option<Vec<String>>,
If we set it to `Option::None`, it means diesel will not update that field.
Empty Vec means update the record and set it to an empty array.

2023-09-28 02:19 UTC, jmbrunskill commented on backend/graphql/notification_query/src/mutations/mod.rs
> +        ModifyNotificationQueryError::NotificationQueryDoesNotExist => {
Fair enough, I think I find it easier to see and understand on different lines, although I do like it for these very related errors though.

2023-09-28 02:21 UTC, jmbrunskill commented on backend/repository/src/db_diesel/notification_query_row.rs
> +*/
Yeah I guess so, will get out of date. I find it a useful reference though...
Hmmm

2023-09-28 02:23 UTC, jmbrunskill commented on backend/service/src/notification_query/tests/create.rs
> +        if !result.is_ok() {
I'm not sure about this pattern, but I've found it kind of helpful when debugging tests. E.g. In this test we're asserting that this result is ok. If it's not ok, we want to see what the actual error was. Probably a better idea is to do assert_eq!() then you'll see the error if it's not ok... Will try that...

2023-09-28 02:29 UTC, jmbrunskill commented on backend/util/src/validate.rs
> +    static ref SPECIAL_CHARS_RE: Regex = Regex::new(r"[^ 0-9A-Za-z_\-@.+:/(),&]").unwrap();
![image](https://github.com/openmsupply/notify/assets/8287373/87cc7bf9-a75e-47d0-bbc3-de3cef90d501)

2023-09-28 02:32 UTC, jmbrunskill commented on backend/service/src/notification_query/tests/create.rs
> +        if !result.is_ok() {
Ok, that's not easy either, as we need to recreate the whole row to check it's ok. Changed to unwrap...

2023-09-28 02:49 UTC, jmbrunskill commented on backend/service/src/notification_query/validate.rs
> +    Ok(name.trim().len() >= 3 && name.len() <= 70)
I guess it could be this, but the point is really to make sure they have a put something other than spaces in the field in, and b) haven't made it too big. (this is copy and pasted from Lache's code)

2023-09-28 02:59 UTC, jmbrunskill commented on backend/graphql/notification_query/src/lib.rs
> +    pub async fn notification_querys(
Cool thanks for the feedback, updated https://github.com/openmsupply/notify/pull/141/commits/ee6986089be9106897a9895831a966e2967be4d8

2023-09-28 03:02 UTC, jmbrunskill commented on backend/util/src/validate.rs
> +    static ref SPECIAL_CHARS_RE: Regex = Regex::new(r"[^ 0-9A-Za-z_\-@.+:/(),&]").unwrap();
Confusion might be that it's matching any non-standard characters.
The list of allowed chars is getting pretty long though, I wonder if it's worth having this check at all? Just allow what ever?

2023-09-28 19:06 UTC, roxy-dao commented on backend/util/src/validate.rs
> +    static ref SPECIAL_CHARS_RE: Regex = Regex::new(r"[^ 0-9A-Za-z_\-@.+:/(),&]").unwrap();
Think it's fine to have the check

2023-09-28 19:20 UTC, roxy-dao approved these changes
LGTM~

2023-09-28 21:46 UTC, merged